/**
 * The service definitions: what a supervisor needs to run the daemon without the app.
 *
 * ## Why the text is here and the installing is not
 *
 * A launchd plist, a systemd unit and a Task Scheduler definition are all *text*, and the text is where every
 * decision lives: the program arguments, when to start, when to restart, and — the line that matters most for this
 * product — `--managed-by service`, which is what makes the daemon's claim say a supervisor owns it and therefore
 * what makes the window leave it alone when it quits.
 *
 * So the text is generated by pure functions here, in `@envoydev/platform`, following the rule the whole package
 * exists for: **the branch for a platform this machine is not runs anyway**, in the suite. `launchctl`, `systemctl`
 * and `schtasks` are the adapter's problem (`docs/daemon-lifecycle.md` §6), and they are thin: load, unload, ask.
 *
 * ## The policies the text encodes, and why each one is in it
 *
 *   * **Start at login, not at boot** (a LaunchAgent, a user unit, a task at logon). The daemon needs the user's
 *     `HOME`, git identity, credential helper and ssh agent, so running it as root or `SYSTEM` would break every git
 *     action in the product. Starting before anyone logs in needs a privileged step on macOS and Windows — a
 *     LaunchDaemon, stored credentials — which is a decision for the person installing it, not a default.
 *   * **Restart on failure, never on a clean stop.** A deliberate stop exits `0`; `KeepAlive { SuccessfulExit: false }`
 *     and systemd's `Restart=always` with `RestartPreventExitStatus=4` (this family's damaged-profile code) mean
 *     "bring it back when it crashed, and leave it down when I meant it". A supervisor that ignored that distinction
 *     would fight the user.
 *   * **Throttle, so a crash loop is not a storm.** launchd's minimum `ThrottleInterval` and systemd's `RestartSec`
 *     are set explicitly rather than left to defaults.
 *   * **Logs go where the daemon already writes them**, so one directory holds the whole story of a restarted daemon:
 *     the log, the restart ledger and the heartbeat file.
 */

// Type-only: erased at runtime, so the barrel that re-exports this module is not a runtime cycle.
import type { PlatformId } from "./index.js";

/** Which supervisor a definition is for. */
export type ServiceKind = "launchd" | "systemd" | "schtasks";

export interface ServiceDefinitionInput {
  /** The OS the definition is for. Passed in, never read from `process.platform` (§ "no platform checks"). */
  platform: PlatformId;
  /** The installed payload's program and entry point — `payloadPaths()` in the daemon. */
  node: string;
  entry: string;
  /** The shared home, so the supervisor starts the daemon against the same state the window reads. */
  home: string;
  /** Where the daemon's output goes. A directory, created by the installer if it is not there. */
  logPath: string;
  /** The launchd label / systemd unit name / task name. */
  label?: string;
}

export interface ServiceDefinition {
  kind: ServiceKind;
  label: string;
  /** Where the file goes, relative to the user's home — the installer joins it. */
  relativePath: string;
  contents: string;
}

/** The default name, in the family's reverse-DNS style. */
export const DEFAULT_SERVICE_LABEL = "dev.envoy.envoydev.daemon";

/** XML text, escaped. A home directory containing `&` is not exotic — and it must not break the file. */
function xml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** systemd splits `ExecStart` on whitespace, so a path with a space must be quoted. */
function systemdArg(value: string): string {
  return /[\s"']/.test(value) ? `"${value.replace(/(["\\])/g, "\\$1")}"` : value;
}

/**
 * The arguments every definition runs.
 *
 * `--home` is an argument rather than only an environment variable because of Windows: a task started at logon
 * inherits whatever environment the session happens to have, and the Task Scheduler's XML has no element for
 * setting one. Passing it here means all three supervisors start the daemon against the same home the window reads
 * without depending on how the user's shell is configured.
 */
function programArguments(input: ServiceDefinitionInput): string[] {
  return [input.node, input.entry, "--home", input.home, "--managed-by", "service"];
}

function launchdDefinition(input: ServiceDefinitionInput, label: string): ServiceDefinition {
  const args = programArguments(input);
  return {
    kind: "launchd",
    label,
    relativePath: `Library/LaunchAgents/${label}.plist`,
    contents: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${xml(label)}</string>
  <key>ProgramArguments</key>
  <array>
${args.map((argument) => `    <string>${xml(argument)}</string>`).join("\n")}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <!-- Restart when it failed, and stay down when it exited 0: a deliberate stop is not a crash. -->
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${xml(input.logPath)}</string>
  <key>StandardErrorPath</key>
  <string>${xml(input.logPath)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>ENVOYMESH_HOME</key>
    <string>${xml(input.home)}</string>
  </dict>
</dict>
</plist>
`,
  };
}

function systemdDefinition(input: ServiceDefinitionInput, label: string): ServiceDefinition {
  const command = programArguments(input).map(systemdArg).join(" ");
  return {
    kind: "systemd",
    label,
    relativePath: `.config/systemd/user/${label}.service`,
    contents: `[Unit]
Description=EnvoyDev daemon (${label})
# Started at login by default. A machine that must run this before anyone logs in needs
# \`loginctl enable-linger <user>\`, which is one privileged step and not this file's business.

[Service]
Type=simple
ExecStart=${command}
Environment=ENVOYMESH_HOME=${systemdArg(input.home)}
# Restart when it failed; exit 4 is this family's damaged-profile code, which no restart can fix, and exit 0 is a
# deliberate stop. Restarting either would fight the person who stopped it.
Restart=always
RestartSec=5
RestartPreventExitStatus=0 4
# Output goes to the journal; the daemon also keeps its own log, ledger and heartbeat under the product's state.

[Install]
WantedBy=default.target
`,
  };
}

function schtasksDefinition(input: ServiceDefinitionInput, label: string): ServiceDefinition {
  // `<Command>` is one path and needs no quoting; `<Arguments>` is a raw command line, so a path with a space
  // must be quoted or the task runs a program that does not exist.
  const argumentLine = [input.entry, "--home", input.home, "--managed-by", "service"]
    .map((argument) => (/\s/.test(argument) ? `"${argument}"` : argument))
    .join(" ");
  return {
    kind: "schtasks",
    label,
    relativePath: `AppData/Local/EnvoyDev/${label}.xml`,
    contents: `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>EnvoyDev daemon</Description>
  </RegistrationInfo>
  <Triggers>
    <!-- At logon, so the daemon runs as this user and can use their git credentials. -->
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${xml(input.node)}</Command>
      <Arguments>${xml(argumentLine)}</Arguments>
    </Exec>
  </Actions>
</Task>
`,
  };
}

/**
 * The definition for this platform, or `undefined` where this build does not know how to install one.
 *
 * `undefined` rather than a guess: a caller that cannot install a service must say so, and inventing a file for a
 * supervisor that does not exist would be exactly the kind of claim the rest of this product refuses to make.
 */
export function serviceDefinition(input: ServiceDefinitionInput): ServiceDefinition | undefined {
  const label = input.label ?? DEFAULT_SERVICE_LABEL;
  if (input.platform === "macos") return launchdDefinition(input, label);
  if (input.platform === "linux") return systemdDefinition(input, label);
  if (input.platform === "windows") return schtasksDefinition(input, label);
  return undefined;
}
